###
POST http://localhost:3000/dashboard/product HTTP/1.1
Content-Type: application/json

{
    "product":"Orange",
    "price": 17,
    "cant": 10,
    "state": true
}

###
POST http://localhost:3000/dashboard/client HTTP/1.1
Content-Type: application/json

{
    "name":"Jacinto",
    "lastname":"Mejía",
    "address": {"city": "Manizales", "code_zip": 13129, "lat": 122, "length": 28},
    "account_banks":"Bancolombia"
}

###
GET  http://localhost:3000/dashboard/clients HTTP/1.1

###
GET  http://localhost:3000/dashboard/products HTTP/1.1

###
GET  http://localhost:3000/dashboard/clients/621470d7bf71619abfbfb622 HTTP/1.1

###
GET  http://localhost:3000/dashboard/products/6214714abf71619abfbfb62d HTTP/1.1

###
DELETE http://localhost:3000/dashboard/clients/621470d7bf71619abfbfb622 HTTP/1.1

###
DELETE http://localhost:3000/dashboard/products/6214714abf71619abfbfb62d HTTP/1.1

###
PUT http://localhost:3000/dashboard/clients/621470d7bf71619abfbfb622 HTTP/1.1
Content-Type: application/json

{
    "name":"Nelson",
    "lastname":"Gallego"
}

###
PUT http://localhost:3000/dashboard/products/6214714abf71619abfbfb62d HTTP/1.1
Content-Type: application/json

{
    "product":"Banana",
    "price": 5
}